name: Changelog - Auto Changelog

on:
  pull_request_target:
    types:
      - closed
    branches:
      - master

permissions:
  contents: write

jobs:
  auto_changelog:
    runs-on: ubuntu-24.04
    if: github.event.pull_request.merged == true

    steps:
      - name: Generate App Token
        id: app-token-generation
        uses: actions/create-github-app-token@v3.2.0
        with:
          client-id: ${{ secrets.APP_CLIENT_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: |
            Horizon-Changelog
            horizon-scripts

      - name: Download autoChangelog.js
        env:
          GH_TOKEN: ${{ steps.app-token-generation.outputs.token }}
        run: |
          FILES=$(gh api repos/horizon-dev-team/horizon-scripts/contents/Changelog --jq '.[].name')
          for file in $FILES; do
            gh api repos/horizon-dev-team/horizon-scripts/contents/Changelog/$file --jq '.content' | base64 -d > $file
          done

      - name: Run auto changelog
        uses: actions/github-script@v9
        with:
          script: |
            const { processAutoChangelog } = await import('${{ github.workspace }}/autoChangelog.js')
            await processAutoChangelog({ github, context })
          github-token: ${{ steps.app-token-generation.outputs.token }}
